name: Build and Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Wait for a few seconds
      run: sleep 10  # 等待10秒钟，可以根据需要调整时间

    - name: Debug Info
      run: |
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "GITHUB_REF: $GITHUB_REF"

    - name: Download release .tar.gz
      run: |
        RELEASE_TAG=${GITHUB_REF#refs/tags/}
        echo "RELEASE_TAG: $RELEASE_TAG"
        RELEASE_URL=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${RELEASE_TAG} | jq -r '.assets[] | select(.name | endswith("_${{ matrix.arch }}.tar.gz")) | .browser_download_url')
        echo "Release URL: $RELEASE_URL"
        if [ -z "$RELEASE_URL" ]; then
          echo "No release asset found for architecture: ${{ matrix.arch }}"
          exit 1
        fi
        curl -L $RELEASE_URL -o release_${{ matrix.arch }}.tar.gz

    - name: Create extraction directory
      run: mkdir -p ./app/autMan

    - name: Extract release .tar.gz
      run: tar -xzf release_${{ matrix.arch }}.tar.gz -C ./app/autMan --strip-components=1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Extract version number from Git tag
      id: extract_version
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/tags/}
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
        echo "Extracted RELEASE_VERSION: ${RELEASE_VERSION}"

    - name: Build Docker image
      run: |
        docker build --platform linux/${{ matrix.arch }} -t ${{ secrets.DOCKER_HUB_USERNAME }}/autman:${{ env.RELEASE_VERSION }}-${{ matrix.arch }} -f Dockerfile .
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/autman:${{ env.RELEASE_VERSION }}-${{ matrix.arch }} ${{ secrets.DOCKER_HUB_USERNAME }}/autman:latest-${{ matrix.arch }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/autman:${{ env.RELEASE_VERSION }}-${{ matrix.arch }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/autman:latest-${{ matrix.arch }}

    - name: Create and push manifest
      if: matrix.arch == 'amd64'
      run: |
        docker manifest create ${{ secrets.DOCKER_HUB_USERNAME }}/autman:${{ env.RELEASE_VERSION }} \
          ${{ secrets.DOCKER_HUB_USERNAME }}/autman:${{ env.RELEASE_VERSION }}-amd64 \
          ${{ secrets.DOCKER_HUB_USERNAME }}/autman:${{ env.RELEASE_VERSION }}-arm64
        docker manifest push ${{ secrets.DOCKER_HUB_USERNAME }}/autman:${{ env.RELEASE_VERSION }}

        docker manifest create ${{ secrets.DOCKER_HUB_USERNAME }}/autman:latest \
          ${{ secrets.DOCKER_HUB_USERNAME }}/autman:latest-amd64 \
          ${{ secrets.DOCKER_HUB_USERNAME }}/autman:latest-arm64
        docker manifest push ${{ secrets.DOCKER_HUB_USERNAME }}/autman:latest
